### ISSUE TITLE
Localized strings; refactor ToC and prefaces

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-jis#13]
Source: https://github.com/metanorma/metanorma-jis/issues/9

DRAFT

Here I'll put the static strings which missing in `/jis-standard/localized-strings/localized-string`.

- permission text on each page footer: `著作権法により無断での複製，転載等は禁止されております。` (translated text `Duplication, reprinting, etc. without permission is prohibited by copyright law.`)
- ToC: `目 次`
- page: `ページ`
- white paper: `白 紙`
- doctype_dict.japanese-industrial-standard: `日本産業規格`
(actually I don't know - white-paper or japanese-industrial-standard is doctype?)

**Comment by ronaldtse** [comment]
> japanese-industrial-standard

Is the doctype.

There are TS and TR also:
* technical-specification: 標準仕様書
* technical-report: 標準報告書

**Comment by opoudjis** [comment]
> ToC: 目 次

table_of_contents: 目次 . 

The added space between the characters is a Presentation issue specific to titles, and I will take care of it: https://github.com/metanorma/metanorma-jis/issues/62  That applies to *all* interpolation of &#x3000; into titles. Once I've implemented https://github.com/metanorma/metanorma-jis/issues/62 , if I miss any, you need to tell me, @Intelligent2013 : I should be handing you in Presentation XML all titles in presentation-ready form.

**Comment by Intelligent2013** [comment]
@opoudjis I can't generate the presentation XML with added spaces:
```xml
<localized-string key="table_of_contents" language="ja">目次</localized-string>
```
My `Gemfile.lock`:
```
GIT
  remote: https://github.com/metanorma/isodoc
  revision: 1ff03d894a36d2e7666cec30f8bcf36a30962c0f
  branch: main
...
GIT
  remote: https://github.com/metanorma/isodoc-i18n
  revision: a8b6afa68ab840e9fed934aaac0ae95b0ff29e4d
  branch: main
...
GIT
  remote: https://github.com/metanorma/metanorma-jis
  revision: c7236a1eb5ccd75b6bbad7c1388413ff1a757300
  branch: main
...
```

**Comment by Intelligent2013** [comment]
@opoudjis we need two localized strings for `table_of_contents`:
- without spaces (for page header, after docidentifier) `<localized-string key="table_of_contents" language="ja">目次</localized-string>`, as currently
- with spaces, for ToC header

**Comment by opoudjis** [comment]
I've just realised that I am not inserting the table of contents Heather into the presentation XML, which is where I would expect the spacing to kick.in. I am going to change that, but it does have knock-on effects on how Word is handled, so it will not be immediate

**Comment by opoudjis** [comment]
So,

I will insert a new element in Presentation XML

`<toc><title>Table of Contents</title></toc>`

at the start of `preface`, and it being a title, it will be subject to Spärdruck in i18n. 

* HTML will find that title (and any other text that might need to accompany it — but I don't expect any), and move it to the sidebar.
* Word and PDF will render the ToC at that location. 
* If the ToC needs to be somewhere else, please tell me to move it appropriately: I will work out the location from the existing PDF implementations
* These will be PRs subject to @Intelligent2013 confirming that the ToCs are located in the right place

This is not strictly speaking a necessary change, except that we now have a mechanism for Word and PDF to synchronise ToC location, which there wasn't before.

This will need to be extended to other ToC types, e.g. figures, tables, and the appropriate `toc` will be inserted if there is something to insert. `toc` will be typed in those instances:

`<toc type="figure"><title>Table of Contents</title></toc>`

There is no reason why I shouldn't populate the contents of the toc, as I've kind of already done with indexes; I won't, because HTML and Word can have different levels of content (e.g. 2 levels deep for HTML, 4 for Word, because there is less space in the HTML sidebar.)

**Comment by Intelligent2013** [comment]
> These will be PRs subject to @Intelligent2013 confirming that the ToCs are located in the right place

@opoudjis `preface/toc` - it's ok for me.

**Comment by Intelligent2013** [comment]
@opoudjis `<clause type="toc">` is ok also.

**Comment by opoudjis** [comment]
Using this opportunity to refactor preface processing in Word/HTML: processes clauses in order found, rather than setting their order in code.

**Comment by Intelligent2013** [comment]
I've updated JIS XSLT for the processing `<clause type="toc">`.

**Comment by Intelligent2013** [comment]
@opoudjis for further updates, if changes relates to all SDOs, then please specify it clearly, or create the tickets in the 'higher level' repository (`metanorma`, `standoc`, `mn-native-pdf`, ...). I've thought that new element `<clause type="toc">` relates to JIS only (because this ticket in `metanorma-jis` repo), but I have to update all XSLT urgently.
